// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spamma.Api.Data.Postgres;

#nullable disable

namespace Spamma.Api.Data.Postgres.Migrations
{
    [DbContext(typeof(SpammaPostgresContext))]
    [Migration("20231112195654_InitMailMessage")]
    partial class InitMailMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spamma.Api.Domain.MailMessage.Aggregate.MailMessage", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("WhenReceived")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("MailMessage", (string)null);
                });

            modelBuilder.Entity("Spamma.Api.Domain.MailMessage.Aggregate.MailMessage", b =>
                {
                    b.OwnsMany("Spamma.Api.Domain.MailMessage.Aggregate.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("ID")
                                .HasColumnType("uuid");

                            b1.Property<int>("AddressType")
                                .HasColumnType("integer");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid?>("MailMessageID")
                                .HasColumnType("uuid");

                            b1.HasKey("ID");

                            b1.HasIndex("MailMessageID");

                            b1.ToTable("Address", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MailMessageID");
                        });

                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
