// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spamma.Api.Data;
using Spamma.Api.Domain;

#nullable disable

namespace Spamma.Api.Data.Sqlite.Migrations
{
    [DbContext(typeof(SpammaContext))]
    [Migration("20231105215627_InitMailMessage")]
    partial class InitMailMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Spamma.Api.Domain.MailMessage.Aggregate.MailMessage", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("WhenReceived")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MailMessage", (string)null);
                });

            modelBuilder.Entity("Spamma.Api.Domain.MailMessage.Aggregate.MailMessage", b =>
                {
                    b.OwnsMany("Spamma.Api.Domain.MailMessage.Aggregate.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("ID")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AddressType")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("MailMessageID")
                                .HasColumnType("TEXT");

                            b1.HasKey("ID");

                            b1.HasIndex("MailMessageID");

                            b1.ToTable("Address", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MailMessageID");
                        });

                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
