openapi: 3.0.3
info:
  title: API Key Management API
  version: 1.0.0
  description: API for managing user API keys

servers:
  - url: https://api.spamma.local
    description: Local development server

security:
  - ApiKeyAuth: []

paths:
  /api/user-management/api-keys:
    get:
      summary: List user's API keys
      description: Retrieve all API keys for the authenticated user
      operationId: listApiKeys
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/ApiKeySummary'
                  totalCount:
                    type: integer
                    example: 5
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create new API key
      description: Create a new API key for the authenticated user
      operationId: createApiKey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                  example: "Production API Key"
      responses:
        '201':
          description: API key created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiKeyCreatedResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: API key name already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/user-management/api-keys/{id}:
    delete:
      summary: Revoke API key
      description: Revoke an API key for the authenticated user
      operationId: revokeApiKey
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '204':
          description: API key revoked successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: API key does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: API key not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ApiKeySummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: "Production API Key"
        createdAt:
          type: string
          format: date-time
          example: "2025-11-10T10:30:00Z"
        isRevoked:
          type: boolean
          example: false
        revokedAt:
          type: string
          format: date-time
          nullable: true
          example: null
      required:
        - id
        - name
        - createdAt
        - isRevoked

    ApiKeyCreatedResponse:
      type: object
      properties:
        apiKey:
          $ref: '#/components/schemas/ApiKeySummary'
        keyValue:
          type: string
          description: The actual API key value - shown only once
          example: "sk-abcd1234efgh5678ijkl9012mnop3456"
      required:
        - apiKey
        - keyValue

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          example: "API_KEY_NAME_EXISTS"
        message:
          type: string
          example: "An API key with this name already exists"
        details:
          type: object
          nullable: true
      required:
        - errorCode
        - message

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    BadRequest:
      description: Invalid request data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication