FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081
EXPOSE 25
EXPOSE 587

# TARGETPLATFORM will be like "linux/amd64" or "linux/arm64"
ARG TARGETPLATFORM
# Copy the pre-published output created on the runner: publish/linux/amd64 or publish/linux/arm64
COPY publish/${TARGETPLATFORM} ./

# Create directories expected by the app
RUN mkdir -p /app/messages /app/certs

ENTRYPOINT ["dotnet", "Spamma.App.dll"]
