name: Build & Push Docker (Manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: timestamp
        run: echo "ts=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test (AMD64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Spamma.App/Spamma.App/Dockerfile.amd64
          target: test
          build-args: |
            BUILD_VERSION=${{ github.event.inputs.tag }}
            BUILD_DATE=${{ steps.timestamp.outputs.ts }}
            VCS_REF=${{ github.sha }}
          cache-from: type=gha

      - name: Build and push (AMD64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Spamma.App/Spamma.App/Dockerfile.amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}-amd64-${{ steps.timestamp.outputs.ts }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64
          build-args: |
            BUILD_VERSION=${{ github.event.inputs.tag }}
            BUILD_DATE=${{ steps.timestamp.outputs.ts }}
            VCS_REF=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (ARM)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Spamma.App/Spamma.App/Dockerfile.arm
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}-arm
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}-arm-${{ steps.timestamp.outputs.ts }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}-arm
          build-args: |
            BUILD_VERSION=${{ github.event.inputs.tag }}
            BUILD_DATE=${{ steps.timestamp.outputs.ts }}
            VCS_REF=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
