# .github/workflows/docker.yml
name: Build Docker Image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build multi-platform image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./src/Spamma.App/Spamma.App/Dockerfile
          tags: spamma:latest