name: Build & Push Docker (Manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: timestamp
        run: echo "ts=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test image for extraction
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Spamma.App/Spamma.App/Dockerfile
          load: true
          target: test
          build-args: |
            BUILD_VERSION=${{ github.event.inputs.tag }}
            BUILD_DATE=${{ steps.timestamp.outputs.ts }}
            VCS_REF=${{ github.sha }}
          tags: spamma:test-extract
          cache-from: type=gha

      - name: Extract test results from Docker
        run: |
          mkdir -p test-results
          docker run --rm -v $(pwd)/test-results:/tmp/out spamma:test-extract \
            sh -c 'if [ -d /test-results ]; then cp -r /test-results/* /tmp/out/; fi' || true
        shell: bash

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'test-results/**/*.trx'
          check_name: Docker Build Test Results
          compare_to_earlier_commit: false

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Spamma.App/Spamma.App/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}-${{ steps.timestamp.outputs.ts }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            BUILD_VERSION=${{ github.event.inputs.tag }}
            BUILD_DATE=${{ steps.timestamp.outputs.ts }}
            VCS_REF=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
