name: Build & Push Docker

on:
  schedule:
    - cron: '2 0 * * *'  # 2 AM UTC daily
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate date tag (for nightly builds)
        id: date
        run: echo "tag=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=nightly-${{ steps.date.outputs.tag }},enable=${{ github.event_name == 'schedule' }}

      - name: Build and test (AMD64)
        run: |
          docker build \
            -f src/Spamma.App/Spamma.App/Dockerfile.amd64 \
            --target test \
            --build-arg BUILD_VERSION="${{ steps.meta.outputs.version }}" \
            --build-arg BUILD_DATE="${{ steps.date.outputs.tag }}" \
            --build-arg VCS_REF="${{ github.sha }}" \
            .

      - name: Build and push (AMD64)
        run: |
          TAGS="${{ steps.meta.outputs.tags }}"
          TAG_ARGS=""
          for tag in $TAGS; do
            TAG_ARGS="$TAG_ARGS -t $tag"
          done
          
          docker build \
            -f src/Spamma.App/Spamma.App/Dockerfile.amd64 \
            --build-arg BUILD_VERSION="${{ steps.meta.outputs.version }}" \
            --build-arg BUILD_DATE="${{ steps.date.outputs.tag }}" \
            --build-arg VCS_REF="${{ github.sha }}" \
            $TAG_ARGS \
            .
          
          for tag in $TAGS; do
            docker push $tag
          done

      - name: Build and push (ARM)
        run: |
          TAGS="${{ steps.meta.outputs.tags }}"
          TAG_ARGS=""
          for tag in $TAGS; do
            TAG_ARGS="$TAG_ARGS -t ${tag}-arm"
          done
          
          docker build \
            -f src/Spamma.App/Spamma.App/Dockerfile.arm \
            --build-arg BUILD_VERSION="${{ steps.meta.outputs.version }}" \
            --build-arg BUILD_DATE="${{ steps.date.outputs.tag }}" \
            --build-arg VCS_REF="${{ github.sha }}" \
            $TAG_ARGS \
            .
          
          for tag in $TAGS; do
            docker push ${tag}-arm
          done
