name: Publish & Build Multi-Arch
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

permissions:
  contents: read
  checks: write
  packages: write

jobs:
  publish:
    name: Build & Test & Publish artifacts for multiple RIDs
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - arch: amd64
            rid: linux-x64
            runs-on: ubuntu-latest
          - arch: arm64
            rid: linux-arm64
            runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish in Docker (${{ matrix.arch }})
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Spamma.App/Spamma.App/Dockerfile.build
          target: publish
          outputs: type=local,dest=publish-output
          platforms: linux/${{ matrix.arch == 'amd64' && 'amd64' || 'arm64' }}

      - name: Upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-${{ matrix.arch }}
          path: publish-output/app/publish

  docker:
    name: Build and push multi-arch image
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download publish artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Organize artifacts for multi-arch build
        run: |
          mkdir -p publish/linux/amd64 publish/linux/arm64
          cp -r artifacts/publish-amd64/* publish/linux/amd64/
          cp -r artifacts/publish-arm64/* publish/linux/arm64/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Spamma.App/Spamma.App/Dockerfile.runtime
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}-amd64
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}-arm
